### PR TITLE
[MRG] CS328 Submission : Group 15

### PR DESCRIPTION
**Pull request by AlphaDecodeX**
Lectures
NPTEL Module 3, Lecture 15 : Building LSH Tables : 2022_04_07_Building_LSH_Tables.ipynb
Group Seq Number
15

Assigned Deadline
07/04/22/Thursday

Members
Lovepreet Singh : 18110094 : lovepreet.singh@iitgn.ac.in : AlphaDecodeX
Vaibhav Dilip Khandare : 18110180 : dilip.khandare@iitgn.ac.in : VaibhavKhandare
Mohammad Taha Syed : 18110169 : mohammad.syed@iitgn.ac.in : soon-to-remove
Any other comments?

### CODE REVIEW

**Comment by yadav-sachin** [comment]
@AlphaDecodeX 
1. Please add the names of the jupyter notebooks/ markdown that you have added in the pull request details.
2. Resolve the merge conflict (it is caused, as I just now merged another PR).
3. Remove `assets/.DS_Store` file from the pull request.

**Comment by yadav-sachin** [comment]
> 1. Please add the names of the jupyter notebooks/ markdown that you have added in the pull request details.

For point 1, just like #18 description of lectures, add name of file and topic.

**Comment by AlphaDecodeX** [comment]
Done Updating the Name and File of the Topic.

**Comment by yadav-sachin** [comment]
@AlphaDecodeX You would have to resolve conflict one more time. 😅 (merged another PR some time back)

**Comment by AlphaDecodeX** [comment]
Sachin Please Merge :)

**Pull request merged**
